import Link from "next/link";

const cards = [
  { icon: "💼", title: "Вакансии", text: "Национальная база вакансий kor.tj позволяет искать предложения работодателей. Это будет основной внешний источник вакансий внутри TJ Smart Guide.", facts: ["Вакансии по профессиям", "Поиск работодателей", "Прямой переход к базе"], href: "https://www.kor.tj/", label: "Открыть вакансии →" },
  { icon: "🏛️", title: "Государственная служба занятости", text: "Органы труда и занятости помогают с поиском работы, профессиональным обучением и другими услугами. Министерство публикует территориальные подразделения.", facts: ["Поиск работы", "Профессиональное обучение", "Территориальные подразделения"], href: "https://mehnat.tj/ru/ministry/territorialdivisions", label: "Найти подразделение →" },
  { icon: "📚", title: "Профессиональное обучение", text: "Государственная система занятости направляет граждан на профессиональную подготовку и переподготовку. Доступные направления зависят от региона и программы.", facts: ["Подготовка", "Переподготовка", "Повышение квалификации"], href: "https://mehnat.tj/ru/activity/employment", label: "Подробнее →" },
  { icon: "🧑‍💻", title: "IT и digital", text: "Для начинающих специалистов полезно собрать резюме, портфолио и список навыков, а затем искать подходящие позиции. TJ Smart Guide может дополнить это персональным планом.", facts: ["Frontend", "Python", "Дизайн и digital"], href: "/plan", label: "Составить карьерный план →" },
  { icon: "📄", title: "Резюме и документы", text: "Подготовьте актуальное резюме и подтверждения образования/квалификации. Для конкретной вакансии приоритет имеют требования работодателя.", facts: ["Резюме", "Образование", "Навыки и опыт"], href: "/plan", label: "Получить план →" },
  { icon: "🌍", title: "Работа за рубежом", text: "В структуре Министерства действует Агентство по трудоустройству за рубежом. Перед поездкой проверяйте официальные условия программы и документы.", facts: ["Официальные программы", "Миграционная информация", "Контакты ведомства"], href: "https://mehnat.tj/ru/ministry/subordinateorganizations", label: "Официальные контакты →" },
];

export default function JobsPage() {
  return <main className="subPage"><div className="subContainer"><nav className="subNav"><Link href="/">🇹🇯 TJ Smart Guide</Link><Link href="/">Главная</Link></nav><header className="pageHeader"><span className="eyebrow">Работа</span><h1>Работа, вакансии и развитие навыков</h1><p>Пользователь должен получить конкретный следующий шаг: открыть вакансии, найти службу занятости, выбрать обучение или собрать карьерный план.</p></header><section className="featureGrid">{cards.map((item) => <article className="featureCard" key={item.title}><div className="guideIcon">{item.icon}</div><h2>{item.title}</h2><p>{item.text}</p><ul>{item.facts.map((fact) => <li key={fact}>{fact}</li>)}</ul><a href={item.href} target={item.href.startsWith("http") ? "_blank" : undefined} rel={item.href.startsWith("http") ? "noreferrer" : undefined}>{item.label}</a></article>)}</section></div></main>;
}
