import Link from "next/link";

const cards = [
  { icon: "🎓", title: "ЦВЭ-2026", text: "Для регистрации НЦТ указывает документ личности, документ об образовании/справку об обучении, подтверждение оплаты при необходимости и документы на льготы. В справочнике также есть порядок регистрации, личный кабинет и результаты.", facts: ["Справочник абитуриента 2026", "Регистрация и документы", "Личный кабинет и результаты"], href: "https://ntc.tj/ru/abiturientu/spravochnik-2026.html", label: "Открыть НЦТ →" },
  { icon: "📅", title: "Календарь поступления", text: "В 2026 году основной этап регистрации на ЦВЭ проходил с 2 марта; НЦТ публикует отдельные объявления по периодам и изменениям сроков.", facts: ["Следить за объявлениями НЦТ", "Проверять свой период", "Не ориентироваться на старые сроки"], href: "https://ntc.tj/ru/", label: "Проверить новости НЦТ →" },
  { icon: "🧾", title: "Документы абитуриента", text: "Для разных категорий абитуриентов требования отличаются. НЦТ публикует таблицы документов отдельно, включая случаи для выпускников 9 и 11 классов.", facts: ["Паспорт/документ личности", "Документ об образовании", "Льготы и особые категории"], href: "https://ntc.tj/ru/abiturientu/spravochnik-2026.html?id=708&view=article", label: "Посмотреть требования →" },
  { icon: "📊", title: "Результаты ЦВЭ", text: "Результаты публикуются в личном кабинете, а НЦТ также использует SMS-уведомления на номер, указанный при регистрации.", facts: ["Личный кабинет", "SMS-уведомление", "Информационные пункты"], href: "https://ntc.tj/images/Downloads/17_rezultati-ekzamenov.pdf", label: "Как получить результаты →" },
  { icon: "🌍", title: "Международные программы", text: "Министерство образования публикует объявления о наборах на международные программы и обучении за рубежом. В каждом объявлении указаны актуальные условия и контакты.", facts: ["Бакалавриат и магистратура", "Стипендии и программы", "Официальные объявления"], href: "https://www.maorif.tj/index.php/news/education", label: "Открыть Минобр →" },
  { icon: "🧭", title: "Персональный план", text: "Если вы не знаете, с чего начать, TJ Smart Guide собирает путь из выбора направления, требований, документов и следующих действий.", facts: ["Выбор направления", "Проверка требований", "Чек-лист подготовки"], href: "/plan", label: "Составить план →" },
];

export default function EducationPage() {
  return <main className="subPage"><div className="subContainer"><nav className="subNav"><Link href="/">🇹🇯 TJ Smart Guide</Link><Link href="/">Главная</Link></nav><header className="pageHeader"><span className="eyebrow">Образование</span><h1>Всё необходимое для поступления и обучения</h1><p>Не отправляем пользователя искать информацию самому. Здесь собраны конкретные данные, чек-листы и прямые ссылки на официальные источники.</p></header><section className="featureGrid">{cards.map((item) => <article className="featureCard" key={item.title}><div className="guideIcon">{item.icon}</div><h2>{item.title}</h2><p>{item.text}</p><ul>{item.facts.map((fact) => <li key={fact}>{fact}</li>)}</ul><a href={item.href} target={item.href.startsWith("http") ? "_blank" : undefined} rel={item.href.startsWith("http") ? "noreferrer" : undefined}>{item.label}</a></article>)}</section></div></main>;
}
